version: "3.1"
services:
    www:
        build:
          context: .
          args:
            DOMAIN: ${DOMAIN}
        ports:
            - "${HOST_HTTP_PORT}:80"
            - "${HOST_HTTPS_PORT}:443"
        volumes:
            - ${HOST_ROOT_PATH}:/var/www/
        links:
            - db:db
        networks:
            - default
    db:
        image: mysql:${MYSQL_VERSION}
        ports:
            - "${HOST_MYSQL_PORT}:3306"
        command: [
          '--character-set-server=${DEFAULT_DB_CHARSET}',
          '--default-authentication-plugin=mysql_native_password'
        ]
        environment:
            MYSQL_DATABASE: ${DEFAULT_DB_NAME}
            MYSQL_USER: ${DEFAULT_DB_USER}
            MYSQL_PASSWORD: ${DEFAULT_DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DEFAULT_DB_ROOT_PASSWORD}
        volumes:
            - ${HOST_MYSQL_PATH}:/var/lib/mysql/
            - ${HOST_DUMP_PATH}:/docker-entrypoint-initdb.d
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - ${HOST_PHPMYADMIN_PORT}:80
        environment:
            MYSQL_USER: ${DEFAULT_DB_USER}
            MYSQL_PASSWORD: ${DEFAULT_DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DEFAULT_DB_ROOT_PASSWORD}
volumes:
    persistent:
